const things: Thing[] = [
  {
    id: 1,
    title: "أبو شلاخ البرمائي",
    year: "2000",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 2,
    title: "أبيات غزل",
    year: "1976",
    publisher: "دار العلوم، الرياض",
    notes: "",
    imageUrl: "/writings/أبيات غزل.jpg",
  },
  {
    id: 3,
    title: "استراحة الخميس",
    year: "2000",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/استراحة الخميس.jpeg",
  },
  {
    id: 4,
    title: "الأشج: قصيدة",
    year: "2001",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/الأشج- قصيدة.jpeg",
  },
  {
    id: 5,
    title: "أشعار من جزائر اللؤلؤ",
    year: "1960",
    publisher: "مطبعة دار الكتب، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 6,
    title: "الأسطورة",
    year: "1997",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 7,
    title: "الإلمام بغزل الفقهاء الأعلام",
    year: "1996",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 8,
    title: "أمريكا والسعودية: حملة إعلامية أم مواجعة سياسية؟!",
    year: "2002",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 9,
    title: "أنت الرياض",
    year: "1977",
    publisher: "المكتب المصري الحديث، القاهرة؛ الإسكندرية",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 10,
    title: "تاريخ اليمن السياسي وعلاقتها بالدبلوماسية",
    year: "1962 - 1948",
    publisher: "جامعة لندن",
    notes: "رسالة دكتوراه",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 11,
    title: "تجربة اليونسكو: دروس الفشل",
    year: "2001",
    publisher: "المجلة العربية، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 12,
    title: "التنمية... الأسئلة الكبرى",
    year: "1982",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 13,
    title: "التنمية وجهًا لوجه",
    year: "1989",
    publisher: "دار تهامة، جدة",
    notes: "ط2",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 14,
    title: "حتى لا تكون فتنة",
    year: "",
    publisher: "",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 15,
    title: "حكاية حب",
    year: "2001",
    publisher: "دار الساقي، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 16,
    title: "الحمى: شعر",
    year: "1982",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 17,
    title: "حياة في الإدارة",
    year: "1998",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 18,
    title: "خواطر في التنمية",
    year: "1977",
    publisher: "دار ثقيف، الطائف",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 19,
    title: "دنسكو",
    year: "2000",
    publisher: "دار الساقي، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 20,
    title: "رجل جاء وذهب",
    year: "2002",
    publisher: "دار الساقي، بيروت؛ لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 21,
    title: "سبعة: رواية",
    year: "1998",
    publisher: "دار الساقي، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 22,
    title: "سحيم",
    year: "1996",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 23,
    title: "سيرة شعرية",
    year: "1980",
    publisher: "دار الفيصل الثقافية، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 24,
    title: "شقة الحرية",
    year: "1994",
    publisher: "رياض الريس، لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 25,
    title: "صوت من الخليج",
    year: "1997",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 26,
    title: "العصفورية",
    year: "1996",
    publisher: "دار الساقي، لندن؛ بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 27,
    title: "عقد من الحجارة",
    year: "1991",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 28,
    title: "عن قبيلتي أحدثكم",
    year: "2001",
    publisher: "دار الزمان، لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 29,
    title: "عن هذا وذاك: مقالات",
    year: "1987",
    publisher: "دار الوطن، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 30,
    title: "العودة إلى الأماكن القديمة",
    year: "1985",
    publisher: "دار الصقر، المنامة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 31,
    title: "العودة سائحًا إلى كاليفورنيا",
    year: "1990",
    publisher: "دار الصافي، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 32,
    title: "العولمة والهوية الوطنية",
    year: "2002",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 33,
    title: "في خيمة شاعر: أبيات مختارة من الشعر القديم والحديث",
    year: "1988-1991",
    publisher: "رياض الريس، لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 34,
    title: "في ذكرى نبيل",
    year: "1969",
    publisher: "مطابع دار الكتب",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 35,
    title: "في رأيي المتواضع",
    year: "1983",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 36,
    title: "قراءة في وجه لندن",
    year: "1997",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 37,
    title: "قصائد أعجبتني",
    year: "1982",
    publisher: "دار ثقيف، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 38,
    title: "قصائد مختارة",
    year: "1990",
    publisher: "دار الفيصل الثقافية، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 39,
    title: "قطرات من ظمأ",
    year: "1965",
    publisher: "مطبعة دار الكتب",
    notes: "ط2",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 40,
    title: "القفص الذهبي: مسرحية",
    year: "1998",
    publisher: "مؤسسة الأيام للصحافة والنشر والتوزيع، المنامة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 41,
    title: "قوافي الجزيرة",
    year: "",
    publisher: "مكتبة الكشكول، لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 42,
    title: "للشهداء",
    year: "2002",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 43,
    title: "اللون عن الأوراد: شعر",
    year: "2000",
    publisher: "دار الساقي، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 44,
    title: "100 من أقوالي غير المأثورة",
    year: "2002",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 45,
    title: "100 ورقة ورد",
    year: "1986",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 46,
    title: "مائة ورقة ياسمين",
    year: "1995",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 47,
    title: "المجموعة الشعرية الكاملة",
    year: "1987",
    publisher: "دار المسيرة، المنامة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 48,
    title: "مرثية فارس سابق: ديوان شعر",
    year: "1990",
    publisher: "دار تهامة، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 49,
    title: "المزيد من رأيي المتواضع",
    year: "1990",
    publisher: "دار الرفاعي، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 50,
    title: "معركة بلا راية",
    year: "1971",
    publisher: "مطبعة دار الكتب، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 51,
    title: "مع ناجي... ومعها",
    year: "1999",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 52,
    title: "من هم الشعراء الذي يتبعهم الغاوون؟",
    year: "1990",
    publisher: "بيت القرآن، البحرين",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 53,
    title: "هل للشعر مكان في القرن العشرين",
    year: "1976",
    publisher: "نادي الطائف الأدبي، الطائف",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 54,
    title: "هما: مسرحية",
    year: "1997",
    publisher: "دار الساقي، بيروت؛ لندن",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 55,
    title: "ورود على ضفائر سناء: شعر",
    year: "1987",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 56,
    title: "واللون عن الأوراد: شعر",
    year: "2000",
    publisher: "دار الساقي، بيروت؛ لندن",
    notes: "باللغتين العربية والإنجليزية",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 57,
    title: "يا فدى ناظريك: شعر",
    year: "2001",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 58,
    title: "الجنية",
    year: "2006",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 59,
    title: "بيت",
    year: "2002",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 60,
    title: "حديقة الغروب: شعر",
    year: "2007",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 61,
    title: "سعادة السفير",
    year: "2003",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 62,
    title: "سلمى",
    year: "2002",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 63,
    title: "ثورة في السنة النبوية",
    year: "2003",
    publisher: "دار الساقي، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 64,
    title: "الخليج يتحدث شعرًا ونثرًا",
    year: "",
    publisher: "",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 65,
    title: "المواسم",
    year: "2006",
    publisher: "مؤسسة دامه، جدة",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 66,
    title: "الوزير المرافق",
    year: "2010",
    publisher: "المؤسسة العربية للدراسات والنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 67,
    title: "استجوبات",
    year: "2010",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "ط2",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 68,
    title: "البراعم: ديوان شعري",
    year: "2008",
    publisher: "دار القمرين، الرياض",
    notes: "ط2",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 69,
    title: "باي باي لندن: ومقالات أخرى",
    year: "2007",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 70,
    title: "أقصوصة ألزهايمر",
    year: "2010",
    publisher: "بيسان للنشر والتوزيع والإعلام، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 71,
    title: "في عين العاصفة",
    year: "2014",
    publisher: "دار جداول للنشر، بيروت",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
  {
    id: 72,
    title: "أبيات القصيد",
    year: "2004",
    publisher: "مكتبة العبيكان، الرياض",
    notes: "",
    imageUrl: "/writings/العصفورية.png",
  },
];

export default things;
